name: RingCraftPlus
version: '1.0-SNAPSHOT'
main: org.randomlima.ringcraftplus.RingCraftPlus
api-version: '1.20'
commands:
  rcpangmarhelmet:
    description: A command that gives the player The Witch King of Angmar.
    usage: /<command>
    permission: rcp.items
  rcppalantir:
    description: A command that gives the player Palantir.
    usage: /<command>
    permission: rcp.items
  rcpgondorhorn:
    description: A command that gives the player the horn of Gondor.
    usage: /<command>
    permission: rcp.items
  rcpgandalfstaff:
    description: A command that gives the player Gandalf's staff.
    usage: /<command>
    permission: rcp.items
  rcpsarumanstaff:
    description: A command that gives the player Saruman's staff.
    usage: /<command>
    permission: rcp.items
  rcpgaladrielphial:
    description: A command that gives the player Galadriel's Phial.
    usage: /<command>
    permission: rcp.items
  rcpradagaststaff:
    description: A command that gives the player Radagast's Staff.
    usage: /<command>
    permission: rcp.items
  rcpwizardhat:
    description: A command that gives the player a wizzard hat.
    usage: /<command>
    permission: rcp.items
  rcpamogusring:
    description: A command that gives the player the amogus ring.
    usage: /<command>
    permission: rcp.items
  rcpurukhaishield:
    description: A command that gives the player the urukhai shield.
    usage: /<command>
    permission: rcp.items
  rcpurukhaisword:
    description: A command that gives the player the urukhai sword.
    usage: /<command>
    permission: rcp.items
  rcpurukhaihelmet:
    description: A command that gives the player the urukhai helmet.
    usage: /<command>
    permission: rcp.items
  rcpbalrogwhip:
    description: A command that gives the player the balrog whip.
    usage: /<command>
    permission: rcp.items